### PR TITLE
JavaScript document issue #1028 is resolved

### PR DESCRIPTION
**Pull request by gyelwande**
Files has been modified for more descriptive message 
Also solved issue # 979

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the pull request @gyelwande !

I think we'll need to change the wording a bit on this. It also mentions some things that are unrelated to the `jobs` table (such as that RethinkDB doesn't use indexes automatically), which we should probably take out.

@chipotle Do you prefer to rewrite this from scratch or modify based on what @gyelwande wrote?

**Comment by chipotle** [comment]
I'll do the editing in a separate ticket. Thanks for the contribution!

**Comment by gyelwande** [comment]
Hi,
I am working on this issue.
https://github.com/rethinkdb/docs/issues/615

I have a doubt. Do we have to to this documentation only for python or same
document will be for all platforms like Java,Javascript etc

Waiting for your reply

Thanks,
Gangadhar

**Comment by danielmewes** [comment]
@gyelwande For https://github.com/rethinkdb/docs/issues/615 there only needs to be one document.

Multiple documents for each language are only required for ReQL API documentation, but #615 is independent of the client used.

**Comment by gyelwande** [comment]
Thank you

**Pull request closed without merging**
