### PR TITLE
add merge on parent node.

### PR DESCRIPTION
**Pull request by sebadiaz**
Very usefull for complex structured component

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the pull requests @sebadiaz . Did you sign the CLA http://www.rethinkdb.com/community/cla/ yet?

Pinging @chipotle for review

**Comment by sebadiaz** [comment]
it is now the case

**Comment by chipotle** [comment]
The more I look at this, the more this looks like it should be a Cookbook recipe rather than a new example in `merge`; a lot of what's going on here is as much the product of `map`/`concatMap` as merging.

Could someone give me an example of a use case for this for the cookbook? I can see what's going on in Sebastian's example, but I'm not clear on when you'd want to do that with real data.

**Comment by danielmewes** [comment]
I'm not sure what a good example use case is.
@sebadiaz did you need this query in a specific context / for a specific application?

**Comment by chipotle** [comment]
Given the age of this pull request and that no more information was provided, I'm closing it. We can re-open (or open a new PR) if necessary.

**Pull request closed without merging**
