### PR TITLE
Update index_create.md

### PR DESCRIPTION
**Pull request by captainpete**
Fix incorrect link

### CODE REVIEW

**Comment by chipotle** [comment]
Thanks for the fix! Have you signed the RethinkDB [CLA](http://www.rethinkdb.com/community/cla/) yet? (I can't easily check, but your name doesn't seem to show up in a git log check.)

**Comment by captainpete** [comment]
Welcome! I read the CLA but have yet to get permission from the employer which involves a yak-shave of process and box ticking. Please someone else, fix the typo independently.. I didn't even spot it, my cat did ;)

**Comment by chipotle** [comment]
I've made this fix in e561e15 in all three files. Thanks for finding the broken link, @captainpete.

**Comment by captainpete** [comment]
Awesome :beer:

**Pull request closed without merging**
