### PR TITLE
add driver for Nim

### PR DESCRIPTION
**Pull request by rgv151**

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the PR @rgv151 .
@chipotle could you take a look at this please?

**Comment by chipotle** [comment]
Hi, and thanks for the pull request. Does this driver support changefeeds? The `changes` term isn't listed in the README file, so I'm not sure.

**Comment by chipotle** [comment]
Derp. @danielmewes pointed out I'd missed it. I was mostly just making sure i'd got the category right. Sorry about that!

More useful question -- have you signed the RethinkDB [CLA](http://www.rethinkdb.com/community/cla/) yet?

**Comment by rgv151** [comment]
almost functions are working well, including `changes`. I just signed CLA. thanks

**Pull request merged**
