### PR TITLE
Stratification sample

### PR DESCRIPTION
**Pull request by sebadiaz**
Add stratification sample

### CODE REVIEW

**Comment by danielmewes** [comment]
Pinging @chipotle for review

**Comment by chipotle** [comment]
This is still worth merging, but needs examples for the other three languages. (I may be able to get to that on my own but no guarantees at this point…)

**Comment by gabor-boros** [comment]
@srh What do you think if we add examples for Python/Ruby/Java? I think it would worth to include it as @chipotle said.

**Comment by srh** [comment]
Seems fine to me.

**Comment by gabor-boros** [comment]
Closing this PR in favor of https://github.com/rethinkdb/docs/pull/1244.

**Pull request merged**
