### PR TITLE
Missing dependency tag in pom.xml example.

### PR DESCRIPTION
**Pull request by ccadieux**
pom.xml example is missing the dependency tag.

Also added missing Connection type.

### CODE REVIEW

**Comment by deontologician** [comment]
:+1: this looks good to me

**Comment by chipotle** [comment]
Thanks for the contribution!

Have you signed the [RethinkDB CLA](http://www.rethinkdb.com/community/cla/) yet? If you have, just leave a note here -- otherwise, please leave a note after it's signed.

**Comment by chipotle** [comment]
Pinging @ccadieux about the CLA

**Comment by ccadieux** [comment]
@chipotle I just signed the CLA.

**Pull request merged**
