### PR TITLE
Add phpReAdmin tool

### PR DESCRIPTION
**Pull request by billbarsch**
phpReAdmin is a opensource php tool to administrate RethinkDb databases. 
Create, rename, update, delete or drop databases, tables and docs, and run ReQL queries in PHP.

### CODE REVIEW

**Comment by danielmewes** [comment]
Thank you for the PR @billbarsch . I've added a comment to your commit.

Have you signed our CLA yet? http://rethinkdb.com/community/cla/

**Comment by billbarsch** [comment]
yes, I signed some days ago

**Comment by chipotle** [comment]
Since you opened #682 with the changes from @danielmewes I'm closing this pull request, and using the other one.

**Comment by billbarsch** [comment]
yes, I signed some days ago.
I created a new pull request with the changes

Em quarta-feira, 18 de março de 2015, Daniel Mewes <notifications@github.com>
escreveu:

**Pull request closed without merging**
