### PR TITLE
Add Gentoo Linux community package to the list

### PR DESCRIPTION
**Pull request by ultrabug**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/
### Description

This PR adds **Gentoo Linux** to the list of community supported packages [1] !

[1] http://www.ultrabug.fr/rethinkdb-on-gentoo-linux/

### CODE REVIEW

**Comment by ultrabug** [comment]
Bump for the community :)

**Comment by AtnNn** [comment]
@ultrabug Thanks! this looks great. I'll test and merge this, and I might be able to publish it too.

What are the requirements and steps to build from source, without using the ebuild? I would love to add those too the gentoo page. Pages for the other distros all have build from source instructions.

**Comment by AtnNn** [comment]
I made a small change (e31f57d) and rebased this into master.

These changes will go live next time we update the site. We're having a few issues right now, it might take a little while.

**Comment by ultrabug** [comment]
Great news @AtnNn thank you!

Nothing more to do than the `emerge` command I documented :)

Cheers

**Pull request closed without merging**
