### PR TITLE
Adding new illustrations to the docs and API command pages

### PR DESCRIPTION
**Pull request by ahruygt**

### CODE REVIEW

**Comment by ahruygt** [comment]
Can someone let me know if I'm doing this correctly?  These are my first pull requests....

**Comment by chipotle** [comment]
Sorry for missing this. They look good -- I'm checking them out and testing to see how they look in the current site.

**Comment by chipotle** [comment]
I've updated this branch so it's in sync with the master branch, with these three illustrations added and linked. @mglukhovsky should let you know how he wants to review it.

**Comment by ahruygt** [comment]
Great!  I'll harass @mglukhovsky if I don't hear anything ;)  Thank you, Watts.

**Comment by ahruygt** [comment]
I committed the changes I made so far.  I built the site and took screenshots (see below).

@chipotle does that look/ sound right to you?  If I commit changes, the pull request should be in good shape, yes?

screen shot 2015-10-23 at 2 40 17 pm
screen shot 2015-10-23 at 2 39 36 pm
screen shot 2015-10-23 at 2 39 47 pm
screen shot 2015-10-23 at 2 39 55 pm
screen shot 2015-10-23 at 2 37 29 pm
screen shot 2015-10-23 at 2 38 13 pm
screen shot 2015-10-23 at 2 40 28 pm
screen shot 2015-10-23 at 2 40 41 pm
screen shot 2015-10-23 at 2 39 11 pm
screen shot 2015-10-23 at 2 19 02 pm
screen shot 2015-10-23 at 2 39 24 pm

**Comment by chipotle** [comment]
It looks good, yes. And if you push changes back to this branch, they'll be added to the pull request.

**Comment by ahruygt** [comment]
@mglukhovsky I believe this PR is ready to go. Some of the old illustrations are still on the site- I have only updated a good amount of them with a new *style*.    The older versions are mostly deeper in the api documentation.

**Comment by ahruygt** [comment]
Ping @mglukhovsky.

**Comment by chipotle** [comment]
This has been hanging around an awfully long time. Is it still relevant?

**Comment by mglukhovsky** [comment]
Yes. @ahruygt, I think we need to rework of some of the images -- this is almost ready to go. Can we chat about it next week?

**Comment by ahruygt** [comment]
screen shot 2016-08-22 at 5 34 29 pm
screen shot 2016-08-23 at 3 09 18 pm
screen shot 2016-08-22 at 5 26 12 pm
screen shot 2016-08-22 at 5 22 30 pm

**Comment by FilipeRamalho** [comment]
Any updates on this ? There are some conflicts, must they be fixed or can they be ignored ?

**Pull request merged**
