### PR TITLE
fix `reduce` example for ruby

### PR DESCRIPTION
**Pull request by aderyabin**

### CODE REVIEW

**Comment by mlucy** [comment]
Thanks @aderyabin.  This fix looks good to me.

Could you sign our CLA at http://rethinkdb.com/community/cla/ if you haven't done so already?

Thanks!

**Comment by mlucy** [comment]
@aderyabin -- did you ever get a chance to look at the CLA?

**Comment by aderyabin** [comment]
I signed 1 month ago or more.

**Comment by mlucy** [comment]
Cool, thanks for the fix!

**Pull request merged**
