### PR TITLE
WIP: docs changes for v2.4

### LINKED ISSUE #1178: Write Hooks and Evictions
Evictions are described in the two comments mentioned here:
https://github.com/rethinkdb/rethinkdb/issues/5823#issuecomment-228455004

Write Hooks are described in the comments here:
https://github.com/rethinkdb/rethinkdb/issues/5813

I'll add more detail to this issue when both are finished with review.

### PR DESCRIPTION
**Pull request by marshall007**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description

Fixes #1178.

- [ ] docs for `set_write_hook`
  - [x] JS
  - [ ] Python
  - [ ] Ruby
- [ ] docs for `get_write_hook`
  - [x] JS
  - [ ] Python
  - [ ] Ruby
- [x] update `table_config` docs to include new `write_hook` field

### CODE REVIEW

**Comment by srh** [comment]
Note we've also got a Java driver.  It will also need actual write hook support, see https://github.com/rethinkdb/rethinkdb/issues/6545.

**Comment by FilipeRamalho** [comment]
Why is this pull request not being anymore developed ?

**Comment by srh** [comment]
@FilipeRamalho Please finish the documentation for Python and Ruby.

**Comment by thelinuxlich** [comment]
r.write_time() also needs docs, right?

**Comment by thelinuxlich** [comment]
I think the PR should cover the insert/update/delete/replace optarg ignoreWriteHook

**Comment by srh** [comment]
Finished in PR #1241.  Includes all of the checklist items and also the ignoreWriteHook optarg.

**Pull request closed without merging**
