### PR TITLE
Removes unnecessary backticks in python/ungroup.md

### PR DESCRIPTION
**Pull request by heinzf**
Makes the formatting of the examples nice again.

### CODE REVIEW

**Comment by danielmewes** [comment]
Good catch!
If you haven't done so yet, would you mind signing our CLA at http://rethinkdb.com/community/cla/ so we can merge this?

**Comment by heinzf** [comment]
Done

**Comment by danielmewes** [comment]
@chipotle Looking at the file, is removing those backticks the right thing to do, or should we also merge the `json` section into the `py` part?

**Comment by heinzf** [comment]
There is a "Result:" missing between the two sections now that I look at the other languages.

**Comment by chipotle** [comment]
This actually looks like a copy and paste borking that happened when I was working on the Java code -- that's the Java example in the midst of the backticks, not a Python example. The correct fix may be me digging back in git history and restoring the screwup.

**Pull request merged**
