### PR TITLE
Copy edits for typos

### PR DESCRIPTION
**Pull request by epc**
Contributor's agreement previously signed.

### CODE REVIEW

**Comment by danielmewes** [comment]
Thank you @epc for fixing this!
Your changes look good.
One last thing before we can merge them: Unless you've done so before, could you please sign our contributor agreement http://rethinkdb.com/community/cla/ ? We require this for legal reasons before we can merge any changes.

**Comment by epc** [comment]
Yes…as noted in my comment I've signed the CLA previously.

**Comment by danielmewes** [comment]
Oops missed that.
Merging. The fixes will go online as soon as we redeploy the website (this will happen on Monday I think).

**Comment by danielmewes** [comment]
@chipotle I merged this in. Hope I did so into the correct branch?

**Comment by chipotle** [comment]
Yep, the master branch is the right one.

**Pull request merged**
