### PR TITLE
relative link didn't work

### PR DESCRIPTION
**Pull request by webmasterkai**
Just added a slash.

### CODE REVIEW

**Comment by danielmewes** [comment]
Thank you for the patch @webmasterkai . I know this seems overly complicated for a small change, but would you mind signing our CLA http://rethinkdb.com/community/cla/ ? We require this for legal reasons before we can merge the pull request.

@chipotle can you take a look at the commit please?

**Comment by webmasterkai** [comment]
Sorry, I thought I did the CLA already. Done now.

**Comment by danielmewes** [comment]
Ah sorry, might be. I didn't actually check. Thanks for signing again. :)

**Comment by chipotle** [comment]
Looks good. Thanks!

**Pull request merged**
